# Generated by Django 4.1.4 on 2022-12-27 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0003_user_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstlogin',
            new_name='fristlogin',
        ),
    ]
