# Generated by Django 4.1.4 on 2023-01-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0008_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_charge',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
