# Generated by Django 4.1.4 on 2023-01-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishalapp', '0010_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fristlogin',
        ),
        migrations.AddField(
            model_name='user',
            name='firstlogin',
            field=models.BooleanField(default=False),
        ),
    ]
